// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjmnmbxdpjjicszupqxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbW5tYnhkcGpqaWNzenVwcXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTA4NTAsImV4cCI6MjA2Njc2Njg1MH0.EvvLu4eNMeOOkUNWZHwmLG97R-LXkrtxwFwSgpyunUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);